onlyBuiltDependencies:
  - esbuild

overrides:
  ajv@<8.18.0: '>=8.18.0'
  html2pdf.js@<0.14.0: '>=0.14.0'
  jspdf@<=3.0.4: '>=4.0.0'
  jspdf@<=4.0.0: '>=4.1.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.1: '>=10.2.1'
