name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flatt-security/setup-takumi-guard-npm@v1
      - run: echo "REPO_NAME_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - run: docker build -t ${{ env.REPO_NAME_LC }}:${{ github.sha }} .
